// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface ContactSectionStoryblok {
  title: string;
  subtitle: string;
  items?: ContactSectionItemStoryblok[];
  component: "ContactSection";
  _uid: string;
  [k: string]: any;
}

export interface ContactSectionItemStoryblok {
  icon: string;
  title: string;
  subtitle: string;
  url: string;
  component: "ContactSectionItem";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}

export interface HeroSectionStoryblok {
  video_cover?: AssetStoryblok;
  video_vimeo_id?: string;
  title: string;
  description: string;
  expertises?: HeroSectionExpertiseItemStoryblok[];
  component: "HeroSection";
  _uid: string;
  [k: string]: any;
}

export interface HeroSectionExpertiseItemStoryblok {
  icon: string;
  label: string;
  component: "HeroSectionExpertiseItem";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (ContactSectionStoryblok | HeroSectionStoryblok | ProjectsGridStoryblok)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface ProjectsGridStoryblok {
  projects?: ProjectsGridItemStoryblok[];
  component: "ProjectsGrid";
  _uid: string;
  [k: string]: any;
}

export interface ProjectsGridItemStoryblok {
  title?: string;
  cover?: AssetStoryblok;
  year?: string;
  duration_in_seconds?: string;
  tags?: ("" | "R&D" | "Narrative" | "AI" | "Edit" | "Color" | "Docu" | "VFX" | "Promo" | "Production")[];
  client?: string;
  role?: ("" | "Creative Director" | "Director" | "Writer" | "Editor" | "Head of Post" | "AI Artist")[];
  created_at?: string;
  video_url?: string;
  video_id: string;
  studio?: string;
  platform?: string;
  component: "ProjectsGridItem";
  _uid: string;
  [k: string]: any;
}
